### PR TITLE
fix navbar layout

### LINKED ISSUE #13: Navbar layout fix
####  Navbar layout needs to be changed. The "Yum Yum logo" should be in the right with `margin-left: 10.5%;` margin and in the middle `Home`, `Explore` and `About` tab should be placed and in the left with `margin-right: 10.5%;`  `Login | Register` and the `Cart` image should be placed 

navbar

### PR DESCRIPTION
**Pull request by sohaibaumer**
Fixes #13 

image

### CODE REVIEW

**Comment by mirazxmondal** [comment]
Layout wise the navbar is perfect but the Yum Yum logo and the Login | Register button along with the cart image needs to be interchanged. 

Yum Yum logo first
then in the middle Home, Explore, About 
after which the Register | Login button along with the cart 

@sohaibaumer commit this change too

**Comment by sohaibaumer** [comment]
sure.

**Comment by sohaibaumer** [comment]
done!

image

**Comment by mirazxmondal** [comment]
@sohaibaumer perfect! thanks for contributing to Yum Yum <3

**Pull request merged**
